/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StarredRouteImport } from './routes/starred'
import { Route as IndexRouteImport } from './routes/index'

const StarredRoute = StarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/starred': typeof StarredRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/starred': typeof StarredRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/starred': typeof StarredRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/starred'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/starred'
  id: '__root__' | '/' | '/starred'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StarredRoute: typeof StarredRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/starred': {
      id: '/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof StarredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StarredRoute: StarredRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
